[WIP]feat: Modify bookinfo
layotto/istio pull request #1
Opened 2022-07-03 14:43 UTC by LXPWing

[ ] redis state
[ ] oss img

2022-07-17 13:34 UTC, LXPWing commented
![image](https://user-images.githubusercontent.com/65880844/179400800-1139d750-951f-426b-a1c0-2be2425da352.png)
![image](https://user-images.githubusercontent.com/65880844/179400886-d22ea9ea-8f82-491e-a4c4-d054f04b0345.png)

样式大概是这样，因为图片用的是相对定位不同的显示器可能会有差异。py调用java的preview service需要修改图2中的地址

2022-07-17 16:58 UTC, LXPWing commented
istio的bookinfo页面，我打算重构下。（官方给的不够美观）

2022-07-18 02:36 UTC, seeflood commented
棒！
但居然不是刻晴 😢 

>istio的bookinfo页面，我打算重构下。（官方给的不够美观）

恩但是有几点要注意的:
- 我记得 bookinfo 会有一些官方测试，发http请求、判断返回结果中有没有某些字，从而判断是否请求成功、是否通过了 bookinfo 测试；所以要改页面的话，需要小心不会跑挂测试
- UI 设计上，最好让 玩实验室的人能意识到“这是 istio 的那个 bookinfo、加了更多功能！”，让用户意识到这是 "istio++"；如果UI改的很花哨，我担心用户认不出来这是 "istio 的 bookinfo"了

2022-07-18 15:42 UTC, LXPWing commented
![image](https://user-images.githubusercontent.com/65880844/179548988-55ef083c-a158-4e9e-8df3-a16e1b63460d.png)
考虑了下，修改布局即可

2022-07-18 15:46 UTC, seeflood commented
@LXPWing Ok. 改布局要注意的是，页面右边还有评分栏（我理解你图上没有评分栏，是因为还没部署评分相关的系统？
![image](https://user-images.githubusercontent.com/26001097/179550151-e1874291-34e4-4e6e-95c3-c1bbd6fffbf9.png)

2022-07-18 15:47 UTC, LXPWing commented
评分栏是调用其他数据库的，本地测试的时候没有启动。

2022-07-18 15:49 UTC, seeflood commented
明白。我意思是 改布局是可以的，记得兼容右边栏就行

2022-07-18 15:50 UTC, seeflood commented
现在已经 ready 可以review了对吧?

2022-07-18 15:53 UTC, LXPWing commented
评分栏在最下面独占一行，应该不会受到影响。可以review了

2022-07-19 06:45 UTC, seeflood commented on samples/bookinfo/src/productpage/productpage.py
> +layottoDetails = {
How about naming it as `previews` instead of `layotto xxxx`?  It's better that we make the code irrelevant with `layotto`

2022-07-19 06:50 UTC, seeflood requested changes

2022-07-19 06:50 UTC, seeflood commented on samples/bookinfo/src/productpage/productpage.py
> +    # TODO 添加img、state接口
Shall we delete this line?

2022-07-19 06:50 UTC, seeflood commented on samples/bookinfo/src/productpage/productpage.py
> +    layottoImg, detailsImg = getLayottoImg(product_id, headers)
Naming issues, same as above

2022-07-19 06:59 UTC, seeflood requested changes

2022-07-19 06:59 UTC, seeflood commented on samples/bookinfo/src/productpage/productpage.py
> +def getLayottoImg(product_id, headers):
How about `getPreviewImg`

2022-07-19 06:59 UTC, seeflood commented on samples/bookinfo/src/productpage/productpage.py
> +def getLayottoState(product_id, headers):
How about `getNewsFeed`

2022-07-19 07:04 UTC, seeflood requested changes

2022-07-19 07:04 UTC, seeflood commented on samples/bookinfo/src/productpage/productpage.py
> +    "name": "http://127.0.0.1:8080",
If we hardcode the url here, the demo can't run with istio
We should get this url using environment variables, like other services did:
![image](https://user-images.githubusercontent.com/26001097/179687291-e61cf5ee-33cb-4d23-bffd-a2edc5ebc551.png)

2022-07-19 13:52 UTC, seeflood requested changes

2022-07-19 13:52 UTC, seeflood commented on samples/bookinfo/src/productpage/templates/productpage.html
> +        <dt>news feed:</dt>{{ newsMsg }}
看起来 news feed 是作为“图书详情”表格里的一行？
news feed 做到图书详情的表格外面、作为单独的部分如何~ 如图：
![image](https://user-images.githubusercontent.com/26001097/179766588-4ab522f2-0d32-4f6b-a547-d6f80e45c204.png)
因为 News Feed 有点像打开网页/app 后的一行广告，（类似于横幅广告），和当前的图书没关系，甚至就是和书无关的广告（比如“快来学做短视频，月入2万”）

2022-07-19 14:23 UTC, LXPWing commented
![image](https://user-images.githubusercontent.com/65880844/179774038-588b8bc8-9157-4c24-9c40-a5998b1a6b81.png)
news feed会不会很长

2022-07-19 14:29 UTC, seeflood commented
@LXPWing emmmmmm 那就限制下字数、缩小字体?

2022-07-19 14:59 UTC, LXPWing commented
我把news feed放到页面最下面然后做一个从右到左的滚动

2022-07-19 15:09 UTC, seeflood commented
@LXPWing 啊这，所以是弹幕效果？
我ok. 要不先合并，等线上实验室搞出来看看效果，有问题到时候再优化

2022-07-19 15:11 UTC, LXPWing commented
👌

2022-07-19 15:11 UTC, merged